<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Alur_model extends CI_Model
{

    public $table = 'alur';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,dari,ke,status');
        $this->datatables->from('alur');
        //add this line for join
        //$this->datatables->join('table2', 'alur.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('alur/read/$1'),'Read')." | ".anchor(site_url('alur/update/$1'),'Update')." | ".anchor(site_url('alur/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all($param='')
    {
        if(!empty($param)){
         foreach ($param as $key => $value) {
        
        $this->db->where($this->table.'.'.$key.' like "%'.$value.'%"');
            
        }
    }
       		$this->db->order_by($this->id, $this->order);
            $this->db->join('status sd', 'sd.id = alur.dari', 'left');
            $this->db->join('status sk', 'sk.id = alur.ke', 'left');
            $this->db->select($this->table.'.*,sk.status as status_ke,sd.status as status_dari');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('dari', $q);
	$this->db->or_like('ke', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('dari', $q);
	$this->db->or_like('ke', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
       $acc = $this->db->insert($this->table, $data);
       return $acc;

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
       $acc = $this->db->update($this->table, $data);
       return $acc;

    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $acc = $this->db->delete($this->table);
       return $acc;

    }

    // get data by id
    function get_status()
    {
        return $this->db->get('status')->result();
    }

}

/* End of file Alur_model.php */
/* Location: ./application/models/Alur_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-14 03:29:57 */
/* http://harviacode.com */