<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nik_model extends CI_Model
{

    public $table = 'nik';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('');
        $this->datatables->from('nik');
        //add this line for join
        //$this->datatables->join('table2', 'nik.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('nik/read/$1'),'Read')." | ".anchor(site_url('nik/update/$1'),'Update')." | ".anchor(site_url('nik/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), '');
        return $this->datatables->generate();
    }

    // get all
    function get_all($param='')
    {
        if(!empty($param)){
         foreach ($param as $key => $value) {
        
        $this->db->where($key.' like "%'.$value.'%"');
            
        }
    }
       		$this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
       $acc = $this->db->insert($this->table, $data);
       return $acc;

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
       $acc = $this->db->update($this->table, $data);
       return $acc;

    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $acc = $this->db->delete($this->table);
       return $acc;

    }

}

/* End of file Nik_model.php */
/* Location: ./application/models/Nik_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-10 09:41:17 */
/* http://harviacode.com */