<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Niks_model extends CI_Model
{

    public $table = 'nik';
    public $id = 'nik';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('nik,nama,alamat,kd_propinsi,kd_kabupaten,kd_kecamatan,kd_kelurahan,rtrw,nm_propinsi,nm_kabupaten,nm_kecamatan,nm_kelurahan');
        $this->datatables->from('niks');
        //add this line for join
        //$this->datatables->join('table2', 'niks.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('niks/read/$1'),'Read')." | ".anchor(site_url('niks/update/$1'),'Update')." | ".anchor(site_url('niks/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'nik');
        return $this->datatables->generate();
    }

    // get all
    function get_all($param='')
    {
        if(!empty($param)){
         foreach ($param as $key => $value) {
        
        $this->db->where($key.' like "%'.$value.'%"');
            
        }
    }
       		$this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('kd_propinsi', $q);
	$this->db->or_like('kd_kabupaten', $q);
	$this->db->or_like('kd_kecamatan', $q);
	$this->db->or_like('kd_kelurahan', $q);
	$this->db->or_like('rtrw', $q);
	$this->db->or_like('nm_propinsi', $q);
	$this->db->or_like('nm_kabupaten', $q);
	$this->db->or_like('nm_kecamatan', $q);
	$this->db->or_like('nm_kelurahan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('kd_propinsi', $q);
	$this->db->or_like('kd_kabupaten', $q);
	$this->db->or_like('kd_kecamatan', $q);
	$this->db->or_like('kd_kelurahan', $q);
	$this->db->or_like('rtrw', $q);
	$this->db->or_like('nm_propinsi', $q);
	$this->db->or_like('nm_kabupaten', $q);
	$this->db->or_like('nm_kecamatan', $q);
	$this->db->or_like('nm_kelurahan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
       $acc = $this->db->insert($this->table, $data);
       return $acc;

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
       $acc = $this->db->update($this->table, $data);
       return $acc;

    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $acc = $this->db->delete($this->table);
       return $acc;

    }

    public function get_propinsi($value='')
    {
        return $this->db->get('propinsi')->result();
        
    }

        // get data by id
    function get_kabupaten($id)
    {
        $this->db->where('propinsi_id', $id);
        return $this->db->get('kabupaten')->result();
    }
        // get data by id
    function get_kecamatan($id)
    {
        $this->db->where('kabupaten_id', $id);
        return $this->db->get('kecamatan')->result();
    }
        // get data by id
    function get_kelurahan($id)
    {
        $this->db->where('kecamatan_id', $id);
        return $this->db->get('kelurahan')->result();
    }   function get_nama_kelurahan($id)
    {
        $this->db->where('kecamatan_id', $id);
        return $this->db->get('kelurahan')->result();
    }

}

/* End of file Niks_model.php */
/* Location: ./application/models/Niks_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-10 09:55:40 */
/* http://harviacode.com */