<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ppat_model extends CI_Model
{

    public $table = 'ppat';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama,alamat,id_user');
        $this->datatables->from('ppat');
        //add this line for join
        //$this->datatables->join('table2', 'ppat.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('ppat/read/$1'),'Read')." | ".anchor(site_url('ppat/update/$1'),'Update')." | ".anchor(site_url('ppat/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all($param='')
    {
        if(!empty($param)){
         foreach ($param as $key => $value) {
        
        $this->db->where($key.' like "%'.$value.'%"');
            
        }
    }
       		$this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('ppat.'.$this->id, $id);
        $this->db->join('user', 'user.id = ppat.id_user', 'left');
        $this->db->select('ppat.*,user.*,user.id as user_id,ppat.id as id_ppat');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('id_user', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('id_user', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
       $acc = $this->db->insert($this->table, $data);
       return $acc;

    }  // insert data
    function insert_user($data)
    {
       $acc = $this->db->insert('user', $data);
       $insert_id = $this->db->insert_id();
       
       return $acc.'.'.$insert_id;

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
       $acc = $this->db->update($this->table, $data);
       return $acc;

    }
    // update data
    function update_user($id, $data)
    {
        $this->db->where($this->id, $id);
       $acc = $this->db->update('user', $data);
       return $acc;

    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $acc = $this->db->delete($this->table);
       return $acc;

    }

}

/* End of file Ppat_model.php */
/* Location: ./application/models/Ppat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-26 22:45:37 */
/* http://harviacode.com */