<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'user';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,username,password,jenis,blokir,nama,jabatan');
        $this->datatables->from('user');
        //add this line for join
        //$this->datatables->join('table2', 'user.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('user/read/$1'),'Read')." | ".anchor(site_url('user/update/$1'),'Update')." | ".anchor(site_url('user/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all($param='')
    {
        if(!empty($param['nama']) ||!empty($param['username']) ){
        
        $this->db->where('nama like "%'.$param['nama'].'%" or username like "%'.$param['username'].'%" ');
            
        }
       		$this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('blokir', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('blokir', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
       $acc = $this->db->insert($this->table, $data);
       return $acc;

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
       $acc = $this->db->update($this->table, $data);
       return $acc;

    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $acc = $this->db->delete($this->table);
       return $acc;

    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-12-04 21:57:38 */
/* http://harviacode.com */